### ISSUE TITLE
NAT should use a fixed-size lookup table

### ISSUE THREAD

**Issue by talex5** [yomimono/mirage-nat#17]
The NAT table tends to become large, and being a hashtable it grows suddenly. On systems without virtual memory (e.g. mirage-xen) this can lead to out-of-memory problems. It might be better to allow preallocating a fixed-size table and expiring entries when it becomes full.

I'm currently trying this as a work-around:

https://github.com/talex5/qubes-mirage-firewall/commit/62aec06be9dd370e59e139208cb715ec5ef6f899

**Comment by yomimono** [comment]
Yes, something like an LRU eviction strategy would be reasonable (and certainly preferable to evicting the whole table!).  I'll put this on my list for 1.0.

**Comment by yomimono** [comment]
I do still intend to implement this; it should be easier now that [ocaml-lru-cache](https://github.com/zoggy/ocaml-lru-cache) exists.

**Comment by talex5** [comment]
Hmm. All those `Array.blit`s are a bit concerning. Surely there's a more efficient way?

**Comment by yomimono** [comment]
https://github.com/pqwy/lru-map is likely a better choice.

**Comment by yomimono** [comment]
mirage-nat-hashtable does this.
